import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/main-navigation";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={saira.className}
      >
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
